### ISSUE TITLE
The problem about nesting css

### ISSUE THREAD

**Issue by ZacharyBear** [prabinmagar/dashboard-ui-with-reactjs#1]
I wonder what VSCode extention had you used.
My vscode does‘t allow me to use the nesting css. But chrome supported it, that‘s embarrassing

**Comment by Joymahanta** [comment]
Download/ update Reactjs Extension.

**Comment by ZacharyBear** [comment]
> Download/ update Reactjs Extension.

You're right, and the [`nesting-selector`](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector) is supported in css 2023.
